export enum TokenType {
  INTEGER = 'INTEGER',
  PLUS = 'PLUS',
  MINUS = 'MINUS',
  MULT = 'MULT',
  DIV = 'DIV',
  EOF = 'EOF',
  LPAREN = '(',
  RPAREN = ')',
  BEGIN = 'BEGIN',
  END = 'END',
  ID = 'ID',
  DOT = 'DOT',
  ASSIGN = 'ASSIGN',
  SEMICOLON = 'SEMICOLON',
  REAL = 'REAL',
  INTEGER_NUM = 'INTEGER_NUM',
  PROGRAM = 'PROGRAM',
  INTEGER_DIV = 'INTEGER_DIV',
  COLON = ':',
  COMMA = ',',
  VAR = 'VAR',
}